version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      args:
        environment: dev
    volumes:
      - ./:/usr/src/app
      - "~/.composer.sh:/root/.composer.sh"
      - "~/.ssh:/root/.ssh-local:ro"
