imports:
    - { resource: games.yaml }

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Models,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Utils\RockPaperScissors\GameStrategies\PlayerStrategyFactory:
        arguments: ['%app.game.rock_paper_scissors.all_elements%', '%app.game.rock_paper_scissors.beats%']

    App\Utils\RockPaperScissors\GameStrategies\SingleElementStrategy:
        factory:   ['@App\Utils\RockPaperScissors\GameStrategies\PlayerStrategyFactory', createPlayerStrategy]
        arguments:
            - 'App\Utils\RockPaperScissors\GameStrategies\SingleElementStrategy'
            - ['%app.game.rock_paper_scissors.element.paper%']

    App\Utils\RockPaperScissors\GameStrategies\RandomStrategy:
        factory:   ['@App\Utils\RockPaperScissors\GameStrategies\PlayerStrategyFactory', createPlayerStrategy]
        arguments:
            - 'App\Utils\RockPaperScissors\GameStrategies\RandomStrategy'
            - '%app.game.rock_paper_scissors.all_elements%'
            -
    App\Utils\RockPaperScissors\PlayersCollectionBuilder:
        calls:
            - [addPlayerStrategy, ['%app.game.rock_paper_scissors.strategy.single_element%', '@App\Utils\RockPaperScissors\GameStrategies\SingleElementStrategy']]
            - [addPlayerStrategy, ['%app.game.rock_paper_scissors.strategy.random%', '@App\Utils\RockPaperScissors\GameStrategies\RandomStrategy']]

    App\Command\PlayRockPaperScissorsCommand:
        arguments:
            $playersParams: '%app.game.rock_paper_scissors.players%'
